version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '6432:5432'
    environment:
      - POSTGRES_DB="${DB_NAME}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - sweet-fantasy

  app:
    build: .
    ports:
      - 3001:3001
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/app
    command: air
    depends_on:
      - db
    networks:
      - sweet-fantasy

networks:
  sweet-fantasy:
    driver: bridge
