GET {{host}}/categories/list
Accept: application/json

###

DELETE {{host}}/categories/delete/4
Accept: application/json

###

POST {{host}}/categories/create
Content-Type: application/json;

{
  "name": "testName1",
  "title": "testTitle2",
  "description": "desc3",
  "keywords": "keywords4",
  "file_id": 24
}

###

PUT {{host}}/categories/update/17
Content-Type: application/json

{
  "name": "updatedName",
  "title": "updatedTitle",
  "description": "updatedDescription",
  "keywords": "updatedKeywords",
  "file_id": 25
}

###

POST {{host}}/products/create
Content-Type: application/json;

{
  "name": "Name",
  "title": "Title",
  "description": "desc",
  "keywords": "keywords4",
  "price": 100,
  "discount": 15,
  "hit_sales": true,
  "category_id": 17,
  "file_id": 21
}

